name: Tree-sitter parser fuzzing
description: Fuzzing of tree-sitter parsers using libFuzzer

branding:
  color: green
  icon: shuffle

inputs:
  directory:
    description: The directory of the grammar
  timeout:
    description: The time to wait if the fuzzer hangs
    default: "10"
  max-time:
    description: The maximum total fuzzing time
    default: "60"
  max-length:
    description: The maximum fuzz input length
    default: "4096"
  tree-sitter-version:
    description: The tree-sitter version to install
    default: v0.21.0

runs:
  using: composite
  steps:
    - name: Install tree-sitter
      uses: tree-sitter/setup-action/lib@v1
      with:
        tree-sitter-ref: ${{inputs.tree-sitter-version}}
    - name: Run the fuzzer
      working-directory: ${{github.action_path}}
      shell: sh
      run: |-
        printf '::group::Running the fuzzer\n'
        export LANG_DIR="$GITHUB_WORKSPACE${LANG_DIR+/}$LANG_DIR"
        make LANG_NAME=$(jq -r .name $LANG_DIR/src/grammar.json)
        printf '::endgroup::\n'
      env:
        TIMEOUT: ${{inputs.timeout}}
        MAX_TIME: ${{inputs.max-time}}
        MAX_LEN: ${{inputs.max-length}}
        LANG_DIR: ${{inputs.directory}}
    - name: Upload fuzzer artifacts
      uses: actions/upload-artifact@v4
      with:
        path: artifacts
        name: fuzzer-artifacts-${{inputs.directory}}
        if-no-files-found: ignore
        retention-days: 7
        overwrite: true
