name: Tree-sitter parser fuzzing
description: Fuzzing of tree-sitter parsers using libFuzzer

branding:
  color: green
  icon: shuffle

inputs:
  directory:
    description: The directory of the grammar
  timeout:
    description: The time to wait if the fuzzer hangs
    default: "10"
  max-time:
    description: The maximum total fuzzing time
    default: "60"
  max-length:
    description: The maximum fuzz input length
    default: "4096"
  tree-sitter-version:
    description: The tree-sitter version to install
    default: v0.21.0

runs:
  using: composite
  steps:
    - name: Cache tree-sitter
      uses: actions/cache@v4
      id: cache
      if: inputs.tree-sitter-version != 'master'
      with:
        path: ${{runner.tool_cache}}/tree-sitter
        key: tree-sitter-${{inputs.tree-sitter-version}}
    - name: Install tree-sitter
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{runner.temp}}
      shell: sh
      run: |-
        printf '::group::Cloning tree-sitter repo\n'
        git clone https://github.com/tree-sitter/tree-sitter --filter=blob:none
        cd tree-sitter && git checkout '${{inputs.tree-sitter-version}}'
        printf '::endgroup::\n'

        printf '::group::Installing tree-sitter lib\n'
        make && make PREFIX="$RUNNER_TOOL_CACHE/tree-sitter" install
        printf '::endgroup::\n'
    - name: Set up tree-sitter paths
      shell: sh
      run: |-
        printf '%s\n' >> "$GITHUB_ENV" \
          "LD_LIBRARY_PATH=$RUNNER_TOOL_CACHE/tree-sitter/lib" \
          "PKG_CONFIG_PATH=$RUNNER_TOOL_CACHE/tree-sitter/lib/pkgconfig"
    - name: Run the fuzzer
      working-directory: ${{github.action_path}}
      shell: sh
      run: |-
        printf '::group::Running the fuzzer\n'
        export LANG_DIR="$GITHUB_WORKSPACE${LANG_DIR+/}$LANG_DIR"
        make LANG_NAME=$(jq -r .name $LANG_DIR/src/grammar.json)
        printf '::endgroup::\n'
      env:
        TIMEOUT: ${{inputs.timeout}}
        MAX_TIME: ${{inputs.max-time}}
        MAX_LEN: ${{inputs.max-length}}
        LANG_DIR: ${{inputs.directory}}
    - name: Upload fuzzer artifacts
      uses: actions/upload-artifact@v4
      with:
        path: artifacts
        name: fuzzer-artifacts-${{inputs.directory}}
        if-no-files-found: ignore
        retention-days: 7
        overwrite: true
