name: Tree-sitter parser fuzzing
description: Fuzzing of tree-sitter parsers using libFuzzer

branding:
  color: green
  icon: shuffle

inputs:
  directory:
    description: The directory of the grammar
  corpus:
    description: The directory of the seed corpus
  timeout:
    description: The time to wait if the fuzzer hangs
    default: "10"
  max-time:
    description: The maximum total fuzzing time
    default: "60"
  max-length:
    description: The maximum fuzz input length
    default: "4096"
  tree-sitter-version:
    description: The tree-sitter version to install
    default: latest

runs:
  using: composite
  steps:
    - name: Install tree-sitter
      uses: tree-sitter/setup-action/lib@v1
      with:
        tree-sitter-ref: ${{inputs.tree-sitter-version}}
    - name: Run the fuzzer
      id: fuzz
      working-directory: ${{github.action_path}}
      shell: bash
      run: |-
        export LANG_DIR="$GITHUB_WORKSPACE${LANG_DIR:+/}$LANG_DIR"
        [[ -z $CORPUS_DIR ]] || export CORPUS_DIR="$GITHUB_WORKSPACE/$CORPUS_DIR"
        printf '::group::Running the fuzzer\n'
        make LANG_NAME=$(jq -r .name $LANG_DIR/src/grammar.json) |& tee >(perl annotate.pl)
        printf '::endgroup::\n'
      env:
        TIMEOUT: ${{inputs.timeout}}
        MAX_TIME: ${{inputs.max-time}}
        MAX_LEN: ${{inputs.max-length}}
        LANG_DIR: ${{inputs.directory}}
        CORPUS_DIR: ${{inputs.corpus}}
    - name: Upload fuzzer artifacts
      uses: actions/upload-artifact@v4
      if: failure() && steps.fuzz.outcome == 'failure'
      with:
        path: ${{github.action_path}}/artifacts/*
        name: fuzzer-artifacts-${{inputs.directory}}
        retention-days: 7
        overwrite: true
